### ISSUE TITLE
Mongodb official backend release deprecates r2d2-mongodb

### ISSUE THREAD

**Issue by Ben-PH** [sfackler/r2d2#106]
As per the r2d2-mongodb [readme](https://gitlab.com/petoknm/r2d2-mongodb/-/commit/969ab7ff8d60afc12e6afa4e6c8d06e51188aca1), we now have a crate that is officially supported and handles connection pool internally. PR #105 updates this in the README, however there may need to be other work done.

I don't know the internal workings of this crate. If r2d2 only refers to r2d2-mongodb in the README, then approving #105, or similar action, will resolve this issue.

**Comment by sfackler** [comment]
Fixed in #105
