### ISSUE TITLE
Add a PooledConnection::pool() method

### ISSUE THREAD

**Issue by pjenvey** [sfackler/r2d2#146]
A method returning the parent `Pool` of a `PooledConnection` could be a useful addition. e.g. [deadpool supports this](https://github.com/bikeshedder/deadpool/issues/105).

**Comment by pjenvey** [comment]
Great question, which in retrospect, makes me consider this issue likely invalid.

A use case for deadpool's `pool` method is the ability to access the connection `Pool`'s `Manager` instance, which is somewhat similar to `r2d2::ManageConnection`. This could be used to e.g. retrieve a Pool level configuration stored on the `Manager` instance from the connection itself.

`r2d2::Pool` doesn't currently provide access to its `manager` like this, so this use case isn't applicable to r2d2 AFAICT.

**Comment by sfackler** [comment]
I'd like to see a concrete use case before adding a feature.
