### ISSUE TITLE
What does r2d2 mean?

### ISSUE THREAD

**Issue by justforcomment** [sfackler/r2d2#150]
Hello! What does r2d2 mean?

**Comment by sfackler** [comment]
> R2-D2 ([/ˌɑːr.tuːˈdiːtuː/](https://en.wikipedia.org/wiki/Help:IPA/English)) or Artoo-Detoo[[1]](https://en.wikipedia.org/wiki/R2-D2#cite_note-6) is a fictional robot character in the [Star Wars](https://en.wikipedia.org/wiki/Star_Wars) franchise created by [George Lucas](https://en.wikipedia.org/wiki/George_Lucas). He has appeared in ten of the eleven theatrical Star Wars films to date, including every film in the "[Skywalker Saga](https://en.wikipedia.org/wiki/Skywalker_Saga)", which includes the original trilogy, the prequel trilogy and the sequel trilogy.
