### ISSUE TITLE
Put in README how to set max open connection

### ISSUE THREAD

**Issue by allan-simon** [sfackler/r2d2#18]
Can the example in the README  include how to set that we don't have to have more than X number of connection open ?

**Comment by sfackler** [comment]
The pool maintains a fixed number of connections, which is specified via the `pool_size` field of the config: http://sfackler.github.io/r2d2/doc/v0.6.1/r2d2/config/struct.Builder.html#method.pool_size

**Comment by allan-simon** [comment]
yes I do understand this method exists, but I was pointing out , as it something one is very likely to want to set  if using a connection pool, it's the kind of thing one want to see directly how to do in the readme :)

**Comment by allan-simon** [comment]
I've seen you've updated the example in the README, thanks a lot
