### ISSUE TITLE
Builder doesn't work across different machines. 

### ISSUE THREAD

**Issue by TheServerAsterisk** [sfackler/r2d2#28]
Perhaps this more of a upstream issue, but I have found that when using a binary on a different machine same OS and same packages are installed and I think even the hardware is the same, I get the error 

```
Result::unwrap()` on an `Err` value: InitializationError(None)
```

I realize that this is error is thrown when the Pool::new get unwrapped, but I am actually blaming the builder object namely 

```
    let config = r2d2::config::Builder::new().pool_size(20).build();
    println!("{:?}", config);
```
config will not print anything which is weird since Builder implements the debug trait. Any thoughts on how to resolve this?

**Comment by sfackler** [comment]
It is definitely printing something. Are you sure you're not overlooking it?

**Comment by sfackler** [comment]
BTW, that error most likely implies that it's failing to connect to the database you have configured.

**Comment by TheServerAsterisk** [comment]
Yea I definitely did overlook it. *Sigh*   Thank you for responding.
