### ISSUE TITLE
Resize connection pool at runtime

### ISSUE THREAD

**Issue by flxo** [sfackler/r2d2#30]
Hi,

First: Great and very easy to use crate! Thanks for that!
This more a question than a issue: Is it possible to resize the pool without loosing the established connections? Of course I could build a new pool but this would result in dropping of all the already established connections. In my use case I'd like to initialise the pool with a small number of connections because of timing restrictions (without disabling the [fail fast feature](http://sfackler.github.io/r2d2/doc/v0.7.1/r2d2/config/struct.Builder.html#method.initialization_fail_fast) in order to get instant feedback) and increase the size later as needed up to a certain limit.
Don't know if it is important: I use the [r2d2 Redis](https://github.com/sorccu/r2d2-redis) crate.

Thanks,

@flxo

**Comment by sfackler** [comment]
Hmm, interesting. How long does it take to connect to Redis?

Making the configuration mutable will be a bit awkward, but I think we do what you're looking for without needing any code changes. Specifically, you can disable `initialization_fail_fast`, and then grab one (or however many you want) connections out of the pool right after starting it.

**Comment by flxo** [comment]
Making the pool mutable sound strange. Maybe moving a pool into new a pool might be a considerable option....
The Redis is not the problem. I just ran some tests with a poor connection (bad wifi and vpn)...
Thanks for the hint! I will try the `initial_fail_fast` and the check one of the connections manually.
