### ISSUE TITLE
Is it possible to create a new connection pool if the servers are offline

### ISSUE THREAD

**Issue by bbigras** [sfackler/r2d2#34]
My application create a pool at startup to connect to one API and right now this API is down so my application can't start. I don't really need the API to be up when I start my application, only when I get a request for it.

Is there a way to do that?

**Comment by sfackler** [comment]
Yep, just set [initialization_fail_fast](http://sfackler.github.io/r2d2/doc/v0.7.1/r2d2/config/struct.Builder.html#method.initialization_fail_fast) to false.

**Comment by bbigras** [comment]
`initialization_fail_fast(false)` works and if I use `min_idle(Some(0))` my application will only try to connect if needed. Nice.

If r2d2 is not able to connect, `pool.get()` will return an error but will still try to connect. It seems to ignore the min_idle set to 0. Is it normal behavior?

**Comment by sfackler** [comment]
I'm not sure it's explicitly intentional, more that it falls out from the implementation and generally feels like a reasonable thing to do - if you're trying to get a connection now, you'll probably be trying to get a connection again in the future.
