### ISSUE TITLE
Could ScheduledThreadPool be shared between Pool?

### ISSUE THREAD

**Issue by nottxy** [sfackler/r2d2#43]
There are many Databases(300 Hundreds of...) need be connected...

There is one `ScheduledThreadPool` for one `Pool`, and one `ScheduledThreadPool` will start 3 threads by default, then there will be about 900 threads started...

It is huge...

So, If the `ScheduledThreadPool` could be shared between Pool, then that would be great

**Comment by sfackler** [comment]
That seems reasonable.

**Comment by nottxy** [comment]
Cool, Is there any plan to support this, or i could send a PR

**Comment by nottxy** [comment]
@sfackler I've send a PR(#44)  to fix this issue
