### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by sgrif** [sfackler/r2d2#45]
0.8.0 included significant breaking changes which have non-obvious migration paths. There is no documentation anywhere in this project of what changed, or how someone should migrate to the latest version. http://keepachangelog.com/ is a reasonable place to start if you're looking for a format to use.

**Comment by sfackler** [comment]
Changes are documented on the release tags: https://github.com/sfackler/r2d2/releases

**Comment by sgrif** [comment]
Thanks for the link! Do you think this could be documented in the README? (It's probably worth creating a `CHANGELOG` file which points there as well)

**Comment by theduke** [comment]
+1 for duplicating the changes in  a `CHANGELOG.md` in the repo.

Just came here with the same problem
