### ISSUE TITLE
Are connections initialized synchronously?

### ISSUE THREAD

**Issue by saghm** [sfackler/r2d2#50]
In version 0.8.x, there's no longer an `initialization_fail_fast` option in the configuration for a Pool. Are connections always initialized synchronously now, or is there no way to achieve this behavior anymore?

**Comment by sfackler** [comment]
The `Builder::build` method acts like `initialization_fail_fast`: https://docs.rs/r2d2/0.8.2/r2d2/struct.Builder.html#method.build

**Comment by saghm** [comment]
Awesome! Sorry for missing this in the docs, and thanks for the quick response!
