### ISSUE TITLE
Error not returned until timeout occurs, no matter the error.

### ISSUE THREAD

**Issue by kdar** [sfackler/r2d2#51]
So I noticed if I use the wrong username, password, port, etc... then I will not get an error back until the connection timeout has occurred. Is the canonical way of dealing with this to use something like the postgres crate directly and make sure the credentials are correct before setting up a pool?

**Comment by sfackler** [comment]
Yeah, you could open one connection up directly to make sure the configuration works. r2d2 doesn't know if an error was transient or permanent so it just has to try until it gives up.

**Comment by kdar** [comment]
Thank you!
