### ISSUE TITLE
Can't work with ffi ; i just want use cgo call the rust lib and hold the pool 

### ISSUE THREAD

**Issue by zhaohansprt** [sfackler/r2d2#57]
error[E0277]: the type `(dyn r2d2::HandleError<postgres::Error> + 'static)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
  --> src/lib.rs:81:5
   |
81 |     catch_unwind(|| {
   |     ^^^^^^^^^^^^ `(dyn r2d2::HandleError<postgres::Error> + 'static)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
   |
   = help: within `*mut *mut r2d2::Pool<r2d2_postgres::PostgresConnectionManager>`, the trait `std::panic::RefUnwindSafe` is not implemented for `(dyn r2d2::HandleError<postgres::Error> + 'static)`
   = note: required because it appears within the type `std::marker::PhantomData<(dyn r2d2::HandleError<postgres::Error> + 'static)>`
   = note: required because it appears within the type `std::ptr::Unique<(dyn r2d2::HandleError<postgres::Error> + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn r2d2::HandleError<postgres::Error> + 'static)>`
   = note: required because it appears within the type `r2d2::config::Config<postgres::Connection, postgres::Error>`
   = note: required because it appears within the type `r2d2::SharedPool<r2d2_postgres::PostgresConnectionManager>`
   = note: required because it appears within the type `std::marker::PhantomData<r2d2::SharedPool<r2d2_postgres::PostgresConnectionManager>>`
   = note: required because it appears within the type `std::sync::Arc<r2d2::SharedPool<r2d2_postgres::PostgresConnectionManager>>`
   = note: required because it appears within the type `r2d2::Pool<r2d2_postgres::PostgresConnectionManager>`
   = note: required because it appears within the type `*mut r2d2::Pool<r2d2_postgres::PostgresConnectionManager>`
   = note: required because it appears within the type `*mut *mut r2d2::Pool<r2d2_postgres::PostgresConnectionManager>`
   = note: required because of the requirements on the impl of `std::panic::UnwindSafe` for `&*mut *mut r2d2::Pool<r2d2_postgres::PostgresConnectionManager>`
   = note: required because it appears within the type `[closure@src/lib.rs:81:18: 90:6 c_sqlurl:&*const i8, c_size:&u16, out:&*mut *mut r2d2::Pool<r2d2_postgres::PostgresConnectionManager>]`
note: required by `catch_unwind`
  --> src/lib.rs:491:1
   |
491| fn catch_unwind<F>(f: F) -> CBoxResult where F: FnOnce() -> CBoxResult + UnwindSafe {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by sfackler** [comment]
You can use AssertUnwindSafe to wrap your closure and make it safe to pass to that method.

**Comment by zhaohansprt** [comment]
i use arc<mutex<pool>> solved this
