### ISSUE TITLE
r2d2 mysql 8.0 can not work.

### ISSUE THREAD

**Issue by damody** [sfackler/r2d2#60]
can see this example project.
https://github.com/damody/r2d2mysql

**Comment by sfackler** [comment]
What about it doesn't work?

**Comment by damody** [comment]
always get time out 
https://github.com/damody/r2d2mysql/blob/81e94cd757eea1c15f0342f7bd75593b32b5a0b9/src/main.rs#L71
and get error
`Commands out of sync; you can\'t run this command now`

**Comment by sfackler** [comment]
That sounds like a Diesel problem

**Comment by damody** [comment]
yes, fix by https://github.com/diesel-rs/diesel/pull/1847
