### ISSUE TITLE
Pool accuracy

### ISSUE THREAD

**Issue by anton-dutov** [sfackler/r2d2#62]
New pool test after 41b268c0eab5b75ad530af700909fee1a1e1c2a5
Test code same as
sfackler/r2d2-postgres#12

Expected: After **idle_timeout** pool redused to **2** connections
Reality: Pool reduced after **max_lifetime** to **3** connections and not renew used connections

Test query

    SELECT a.pid, a.backend_start, a.query_start FROM pg_stat_activity a WHERE a.datid IS NOT NULL ORDER BY a.pid;

At  begin

    15490 / 2018-09-28 09:19:49.329870 / 2018-09-28 09:19:49.332444
    15491 / 2018-09-28 09:19:49.330124 / 2018-09-28 09:19:52.336268
    15492 / 2018-09-28 09:19:49.332135 / 2018-09-28 09:19:49.334726
    15493 / 2018-09-28 09:19:49.333422 / 2018-09-28 09:19:49.334606

After around 1min (**max_lifetime** = Duration::from_secs(60))

    15491 / 2018-09-28 09:19:49.330124 / 2018-09-28 09:20:19.360589
    15620 / 2018-09-28 09:20:19.349820 / 
    15621 / 2018-09-28 09:20:19.333852 / 

After 2min

    15491 / 2018-09-28 09:19:49.330124 / 2018-09-28 09:21:21.400551
    19526 / 2018-09-28 09:21:19.334243 / 
    19527 / 2018-09-28 09:21:19.341293 / 

So, what happens if we use **two** connections instead of **one**?

        loop {
            println!("LOOP");
            let db1 = pool.get();
            println!("1/{} {:?}", db_max, db1.is_ok());

            let db2 = pool.get();
            println!("2/{} {:?}", db_max, db2.is_ok());

            std::thread::sleep(Duration::from_secs(1));
        }

After few minutes

    435   / 2018-09-28 09:59:27.376183 / 
    436   / 2018-09-28 09:59:27.377418 /
    32146 / 2018-09-28 09:53:57.376039 / 2018-09-28 09:59:26.856081
    32147 / 2018-09-28 09:53:57.376298 / 2018-09-28 09:59:26.856594

After more time used connections renew, but pool size not reduced

    1447  / 2018-09-28 10:12:57.381760
    1448  / 2018-09-28 10:12:57.381966
    32146 / 2018-09-28 09:53:57.376039 / 2018-09-28 10:13:07.963099
    32147 / 2018-09-28 09:53:57.376298 / 2018-09-28 10:13:07.963322

Same behavior on v0.8.2

**Comment by anton-dutov** [comment]
Sorry for missunderstanding "Sets the minimum idle connection count maintained by the pool." expected min_idle = min_size
But 
min_size = active_connections + min_idle

**Comment by sfackler** [comment]
Sorry, I'm not sure what you mean by that.

**Comment by anton-dutov** [comment]
Nope, current behavior is very usefull
