### ISSUE TITLE
how to drop a connection? 

### ISSUE THREAD

**Issue by karasjoh000** [sfackler/r2d2#67]
Hey, I was wondering when I would know a connection is dropped? Is it when it leaves scope? I just need to configure some things using one of the pooled connections and then drop it right away before launching the backend.

**Comment by davidpdrsn** [comment]
The connection will be put back when it leaves scopes. Rust will call the [`Drop` implementation for PooledConnection](https://docs.rs/r2d2/0.8.3/r2d2/struct.PooledConnection.html#impl-Drop) which puts the connection back into the pool.

You can call [`std::mem::drop`](https://doc.rust-lang.org/std/mem/fn.drop.html) to explicitly drop it ahead of time, or wrap your code in a another scope.

```rust
{
    let connection = pool.get().unwrap();
    // do stuff with `connection`
    // `connection` is dropped
}

// `connection` no longer in scope, so it has been dropped
```
