### ISSUE TITLE
unclear panic message on pool new if database cannot be reach

### ISSUE THREAD

**Issue by wescande** [sfackler/r2d2#87]
### Versions
* **Rust:** rustc 1.37.0-nightly (8ebd67e4e 2019-06-27)  and rust in https://github.com/emk/rust-musl-builder
* **Diesel:** 1.4.2 [feature  postgres + r2d2]
* **Database:** Postresql
* **Operating System** Linux (Docker in aws cloud ECS And Manjaro)

## Problem Description
Pool creation panic without clear log
This is my code :
```
let manager = ConnectionManager::<PgConnection>::new(DATABASE_URL);
let pool = Pool::new(manager).expect("Failed to create pool");
```
But I made a mistake and I open the port of DATABASE_URL to the wrong IP (or just give it the wrong port). It panic and I have no clue to found what was the root cause.
### What is the expected output?

> thread 'main' panicked at 'Failed to create pool: Error(EXPLICIT_MESSAGE)', src/libcore/result.rs:999:5

where EXPLICIT_MESSAGE could be something like "cannot reach database" or "connection failed", or even better if possible "host is up but port is filtered".

### What is the actual output?
> thread 'main' panicked at 'Failed to create pool: Error(None)', src/libcore/result.rs:999:5

### Steps to reproduce
Setup your database and do not open port on the server, or do not allow the diesel server ip or set the wrong (closed)port.
Then start your pool.
There should be a 30 sec wait (more or less, on my computer it's 38s)
Then it panic with the Error(none) message

**Comment by sfackler** [comment]
The error returned from get should contain the last error returned by a connection attempt, but the fact that it's `None` seems to imply to me that none of the individual PgConnection attempts actually completed by the time the constructor gave up after 30 seconds.

For example, this is that I see when running [this test](https://github.com/sfackler/r2d2-postgres/blob/master/src/lib.rs#L17-L35) without Postgres running:

```
thread 'src/lib.rs - PostgresConnectionManager (line 16)' panicked at 'test executable failed:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("error connecting to server: Connection refused (os error 61)"))', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by prettynatty** [comment]
I have the same problem when my container running on gke is misconfigured to connect to a wrong ip without Postgres on it.
