### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by dataf3l** [sfackler/r2d2#89]
It would be nice if the documentation had examples on how to create mysql, postgres and sqlite connection pools, since the "FooDB" doesn't exist.

**Comment by sfackler** [comment]
https://github.com/outersky/r2d2-mysql#example
https://github.com/sfackler/r2d2-postgres#example
https://docs.rs/r2d2_sqlite/0.11.0/r2d2_sqlite/#example

**Comment by dataf3l** [comment]
Thank you for providing these examples!, this is exactly what I needed!, does in your opinion makes sense to add them to the readme or the rustdoc, so that people can find them with relative ease?

**Comment by sfackler** [comment]
I don't think it would make sense to have hundreds of lines of examples for 10+ databases in this crates README.

**Comment by dataf3l** [comment]
I understand.
How do you feel about a repo with examples, and a link in the docs to said repo?
Also, may I know the names of the 10 DBs ?

**Comment by sfackler** [comment]
They are listed in the README: https://github.com/sfackler/r2d2#r2d2

**Comment by dataf3l** [comment]
So I'll just assume this means, no changes will be made.

I understand.
