### ISSUE TITLE
Wiki and Runtime Considerations

### ISSUE THREAD

**Issue by mattlockyer** [sfackler/r2d2#92]
I started a Wiki to document some of the runtime situations people can expect.

https://github.com/sfackler/r2d2/wiki/Runtime-Assumptions-and-Conditions

Also my question about when there are no more connections in the pool, what happens?

IMHO there should be a timeout config and then some busy error returned. So a future could wait for a connection and optionally retry.

**Comment by sfackler** [comment]
It waits for the configured timeout and then returns an error: https://docs.rs/r2d2/0.8.5/r2d2/struct.Builder.html#method.connection_timeout

**Comment by mattlockyer** [comment]
Thanks I'll link to this.
